-- 코드를 작성해주세요
 SELECT ID, FISH_NAME, LENGTH
 FROM
   (SELECT T.ID AS ID,F.FISH_NAME, T.LENGTH,
        RANK() OVER(PARTITION BY T.FISH_TYPE ORDER BY T.LENGTH DESC)    
    AS ranking
    FROM FISH_INFO AS T INNER JOIN FISH_NAME_INFO AS F 
            ON T.FISH_TYPE = F.FISH_TYPE
        ORDER BY ID ASC) AS A
    WHERE ranking = 1
    
        
