-- 코드를 입력하세요
-- 2022년 10월에 작성된 게시글 제목, 게시글 ID, 댓글 ID, 댓글 작성자 ID, 댓글 내용, 댓글 작성일을 조회하는 SQL문

SELECT b.TITLE, b.BOARD_ID, r.REPLY_ID, r.WRITER_ID, r.CONTENTS, r.CREATED_DATE
    FROM USED_GOODS_BOARD AS b
    INNER JOIN USED_GOODS_REPLY AS r ON b.BOARD_ID = r.BOARD_ID
    WHERE b.CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31'
    ORDER BY r.CREATED_DATE ASC, b.TITLE ASC;
    